### ISSUE TITLE
TaskList

### ISSUE THREAD

**Issue by eiri** [eiri/horrible-hash#6]
- [x] Finish with `each` #1
- [x] Beef eunits to be more testy #2
- [x] Add code coverage (Current: 97%)
- [x] Drop in travis #3
- [x] Write specs #4
- [x] Add dialyzer analyzer
- [x] Write @docs #5
- [x] Give the module gh-pages just to check how it works

**Comment by eiri** [comment]
Done
